THAI_TO_PYTHON = {
    "เท็จ": "False",
    "รอ": "await",
    "อื่น": "else",
    "นำเข้า": "import",
    "ผ่าน": "pass",
    "ไม่มี": "None",
    "หยุด": "break",
    "ยกเว้น": "except",
    "ใน": "in",
    "ยก": "raise",
    "จริง": "True",
    "คลาส": "class",
    "สุดท้าย": "finally",
    "คือ": "is",
    "คืนค่า": "return",
    "และ": "and",
    "ทำต่อ": "continue",
    "สำหรับ": "for",
    "แลมบ์ดา": "lambda",
    "ลอง": "try",
    "เป็น": "as",
    "นิยาม": "def",
    "จาก": "from",
    "นอกเขต": "nonlocal",
    "ขณะ": "while",
    "ยืนยัน": "assert",
    "ลบ": "del",
    "ทั่วไป": "global",
    "ไม่": "not",
    "ด้วย": "with",
    "อะซิงค์": "async",
    "หรือถ้า": "elif",
    "ถ้า": "if",
    "หรือ": "or",
    "ให้": "yield",
}

PYTHON_TO_THAI = {v: k for k, v in THAI_TO_PYTHON.items()}
